### ISSUE TITLE
Myanmar Date/Time not included

### ISSUE THREAD

**Issue by bksubhuti** [elementary/switchboard-plug-datetime#78]
Myanmar Date and Time is not included in date time setup.

Anki seems to complain if I manually set the date and time.
There is no choice for "Myanmar (Burma)"

**Comment by getsnoopy** [comment]
I see "Yangon" (Rangoon), which is the capital of Myanmar/Burma.

**Comment by danirabbit** [comment]
Yeah this list comes from an upstream project and it looks like Yangon is what we have from upstream instead of Myanmar/Burma. So this would have to be taken up with the upstream list of timezones.

Closing as "Out of scope" since we don't supply the list of timezones ourself, we just read them from upstream
